export const initialState = {
  posts: [
    {
      title: "WAR",
      id: "1",
      content: "War is coming to us!",
      img: "/img/scover.jpg",
      imgDescription: "My face",
      publishDate: "2022-04-01",
      latestUpdate: "2022-04-02",
      authorEmail: "scoverstudio@gmail.com",
      status: "published",
    },
    {
      title: "RONDO",
      id: "2",
      content: "Big rondo is big!",
      publishDate: "2022-04-12",
      latestUpdate: "2022-04-19",
      price: "25",
      authorEmail: "wacek@gmail.com",
      status: "published",
    },
    {
      title: "WOW",
      id: "3",
      content: "BIGGY",
      localization: "Poland",
      publishDate: "2022-04-12",
      latestUpdate: "2022-04-20",
      authorEmail: "wacek@gmail.com",
      status: "published",
    },
    {
      title: "ALL",
      id: "4",
      content: "BIGGY",
      price: "25",
      localization: "Poland",
      image: "/img/scover.jpg",
      imageDescription: "My face",
      tel: "205-222-223",
      publishDate: "2022-04-12",
      latestUpdate: "2022-04-20",
      authorEmail: "wacek@gmail.com",
      status: "published",
    },
  ],
};
